#!/usr/bin/env python3
from getpass import getpass
from hashlib import sha1
from urllib.request import Request, urlopen

pw_hash = sha1(getpass().encode("utf-8")).hexdigest()
hash_prefix = pw_hash[:5]
hash_suffix = pw_hash[5:].upper().encode("ascii")

url = f"https://api.pwnedpasswords.com/range/{hash_prefix}"
request = Request(url, headers={"User-Agent": "API Client"}, method="GET")

for line in urlopen(request):
    response_hash_suffix, count = line.split(b":")
    count = count.strip().decode("ascii")

    if response_hash_suffix == hash_suffix:
        print(f"The provided password has been leaked {count} times.")
        break
else:
    print("The provided password has not been found.")
